services:
  - type: web
    name: nightscout
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: Europe/Warsaw
